export function getKitchenXRuntimeScript() {
  return [
    '(function(){',
    '  \"use strict\";',
    '  var menuCache = {};',
    '  var menuPromise = {};',
    '  var cart = { items: [], kitchenId: null, listeners: [] };',
    '  function notify(){ cart.listeners.forEach(function(fn){ try{ fn(); }catch(e){} }); }',
    '  function subscribe(fn){ cart.listeners.push(fn); return function(){ cart.listeners = cart.listeners.filter(function(l){ return l !== fn; }); }; }',
    '  function setKitchen(id){ if(!id) return; cart.kitchenId = id; }',
    '  function addItem(item, qty){ if(!item || !item.id) return; var q = Math.max(1, qty || 1);',
    '    var existing = cart.items.find(function(it){ return it.id === item.id; });',
    '    if(existing){ existing.quantity += q; } else { cart.items.push({ id: item.id, name: item.name, price: item.price, vatRate: item.vatRate || 0, quantity: q }); }',
    '    notify();',
    '  }',
    '  function updateQty(id, qty){ var q = Math.floor(qty || 0); if(q <= 0){ cart.items = cart.items.filter(function(it){ return it.id !== id; }); }',
    '    else { cart.items = cart.items.map(function(it){ return it.id === id ? Object.assign({}, it, { quantity: q }) : it; }); }',
    '    notify();',
    '  }',
    '  function totals(){ var subtotal = 0; var vat = 0; cart.items.forEach(function(it){ var base = it.price * it.quantity; subtotal += base; vat += base * (it.vatRate || 0) / 100; });',
    '    return { subtotal: subtotal, vat: vat, total: subtotal + vat }; }',
    '  function normalizeBase(base){ if(!base) return \"\"; return base.endsWith(\"/\") ? base.slice(0,-1) : base; }',
    '  function resolveApiBase(el){ var attr = el.getAttribute(\"data-api-base\"); if(attr) return normalizeBase(attr);',
    '    if(window.__KX_API_BASE__) return normalizeBase(window.__KX_API_BASE__);',
    '    return normalizeBase(window.location.origin); }',
    '  function resolveDomain(el){ var attr = el.getAttribute(\"data-domain\"); return attr && attr.trim() ? attr.trim() : window.location.hostname; }',
    '  function parseBool(val, fallback){ if(val === null || val === undefined) return fallback; if(val === \"false\") return false; if(val === \"true\") return true; return fallback; }',
    '  function parseIntSafe(val, fallback){ var n = parseInt(val || \"\", 10); return Number.isFinite(n) ? n : fallback; }',
    '  function createEl(tag, className, text){ var el = document.createElement(tag); if(className) el.className = className; if(text !== undefined && text !== null) el.textContent = text; return el; }',
    '  function clearEl(el){ while(el.firstChild) el.removeChild(el.firstChild); }',
    '  function formatMoney(value){ if(!Number.isFinite(value)) return \"\"; return value.toFixed(2) + \" SAR\"; }',
    '  function fetchMenu(domain, apiBase){ var key = apiBase + \"|\" + domain; if(menuCache[key]) return Promise.resolve(menuCache[key]);',
    '    if(menuPromise[key]) return menuPromise[key];',
    '    var url = normalizeBase(apiBase) + \"/api/v1/kitchenx/public/menu?domain=\" + encodeURIComponent(domain);',
    '    menuPromise[key] = fetch(url, { credentials: \"include\" }).then(function(res){ if(!res.ok){ return res.text().then(function(t){ throw new Error(t || \"Failed to load menu\"); }); } return res.json(); })',
    '      .then(function(data){ menuCache[key] = data; delete menuPromise[key]; return data; })',
    '      .catch(function(err){ delete menuPromise[key]; throw err; });',
    '    return menuPromise[key];',
    '  }',
    '  function renderMenu(el){',
    '    var domain = resolveDomain(el);',
    '    var apiBase = resolveApiBase(el);',
    '    var columns = Math.max(1, parseIntSafe(el.getAttribute(\"data-columns\"), 3));',
    '    var showImages = parseBool(el.getAttribute(\"data-show-images\"), true);',
    '    var showPrices = parseBool(el.getAttribute(\"data-show-prices\"), true);',
    '    var showAdd = parseBool(el.getAttribute(\"data-show-add-to-cart\"), true);',
    '    var showTabs = parseBool(el.getAttribute(\"data-show-category-tabs\"), true);',
    '    var filterRaw = el.getAttribute(\"data-category-filter\") || \"\";',
    '    var filter = filterRaw ? filterRaw.split(\",\").map(function(v){ return parseIntSafe(v, -1); }).filter(function(v){ return v > 0; }) : [];',
    '    var tabsRoot = el.querySelector(\"[data-kx-menu-tabs]\");',
    '    var itemsRoot = el.querySelector(\"[data-kx-menu-items]\");',
    '    if(!tabsRoot){ tabsRoot = createEl(\"div\", \"\", \"\"); el.appendChild(tabsRoot); }',
    '    if(!itemsRoot){ itemsRoot = createEl(\"div\", \"\", \"\"); el.appendChild(itemsRoot); }',
    '    fetchMenu(domain, apiBase).then(function(data){',
    '      if(!data || !data.categories) return;',
    '      setKitchen(data.kitchen && data.kitchen.id);',
    '      var categories = data.categories;',
    '      if(filter.length){ categories = categories.filter(function(cat){ return filter.indexOf(cat.id) !== -1; }); }',
    '      var activeId = el.__kxActiveCategory || (categories[0] && categories[0].id);',
    '      if(!activeId && categories[0]) activeId = categories[0].id;',
    '      el.__kxActiveCategory = activeId;',
    '      clearEl(tabsRoot);',
    '      if(showTabs && categories.length > 1){',
    '        var tabsWrap = createEl(\"div\", \"flex flex-wrap gap-2 mb-4\");',
    '        categories.forEach(function(cat){',
    '          var isActive = cat.id === activeId;',
    '          var btn = createEl(\"button\", isActive ? \"px-3 py-1 rounded-md bg-primary text-surface\" : \"px-3 py-1 rounded-md border border-muted text-text\", cat.name);',
    '          btn.type = \"button\";',
    '          btn.addEventListener(\"click\", function(){ el.__kxActiveCategory = cat.id; renderMenu(el); });',
    '          tabsWrap.appendChild(btn);',
    '        });',
    '        tabsRoot.appendChild(tabsWrap);',
    '      }',
    '      clearEl(itemsRoot);',
    '      var active = categories.find(function(cat){ return cat.id === activeId; }) || categories[0];',
    '      if(!active) return;',
    '      var grid = createEl(\"div\", \"\");',
    '      grid.style.display = \"grid\";',
    '      grid.style.gridTemplateColumns = \"repeat(\" + columns + \", minmax(0, 1fr))\";',
    '      grid.style.gap = \"16px\";',
    '      active.items.forEach(function(item){',
    '        var card = createEl(\"article\", \"border border-muted rounded-md overflow-hidden\");',
    '        if(showImages && item.image){',
    '          var img = document.createElement(\"img\"); img.src = item.image; img.alt = item.name || \"\"; img.style.width = \"100%\"; img.style.height = \"180px\"; img.style.objectFit = \"cover\";',
    '          card.appendChild(img);',
    '        }',
    '        var body = createEl(\"div\", \"p-3\");',
    '        var header = createEl(\"div\", \"flex items-start justify-between gap-2\");',
    '        header.appendChild(createEl(\"h3\", \"text-base font-semibold\", item.name));',
    '        if(showPrices){ header.appendChild(createEl(\"span\", \"text-sm font-medium\", formatMoney(parseFloat(item.price || 0)))); }',
    '        body.appendChild(header);',
    '        if(item.description){ body.appendChild(createEl(\"p\", \"text-sm opacity-80 mt-2\", item.description)); }',
    '        if(showAdd){',
    '          var addBtn = createEl(\"button\", \"mt-3 inline-flex items-center justify-center px-3 py-1.5 rounded-md bg-primary text-surface\", \"Add to cart\");',
    '          addBtn.type = \"button\";',
    '          addBtn.addEventListener(\"click\", function(){ addItem({ id: item.id, name: item.name, price: parseFloat(item.price || 0), vatRate: parseFloat(item.vat_percent || 0) }, 1); });',
    '          body.appendChild(addBtn);',
    '        }',
    '        card.appendChild(body);',
    '        grid.appendChild(card);',
    '      });',
    '      itemsRoot.appendChild(grid);',
    '    }).catch(function(err){',
    '      clearEl(itemsRoot);',
    '      itemsRoot.appendChild(createEl(\"div\", \"text-sm text-primary\", err && err.message ? err.message : \"Unable to load menu.\"));',
    '    });',
    '  }',
    '  function renderCart(el){',
    '    if(el.__kxCartBound) return; el.__kxCartBound = true;',
    '    var apiBase = resolveApiBase(el);',
    '    var paymentMethod = el.getAttribute(\"data-payment-method\") || \"card\";',
    '    var successUrl = el.getAttribute(\"data-success-url\") || \"\";',
    '    var cancelUrl = el.getAttribute(\"data-cancel-url\") || successUrl;',
    '    var itemsRoot = el.querySelector(\"[data-kx-cart-items]\");',
    '    var totalsRoot = el.querySelector(\"[data-kx-cart-totals]\");',
    '    var errorRoot = el.querySelector(\"[data-kx-cart-error]\");',
    '    function update(){',
    '      if(!itemsRoot || !totalsRoot) return;',
    '      clearEl(itemsRoot);',
    '      if(cart.items.length === 0){',
    '        itemsRoot.appendChild(createEl(\"div\", \"text-sm opacity-75\", \"Your cart is empty.\"));',
    '      } else {',
    '        cart.items.forEach(function(item){',
    '          var row = createEl(\"div\", \"flex items-center justify-between gap-3\");',
    '          var info = createEl(\"div\", \"\");',
    '          info.appendChild(createEl(\"div\", \"text-sm font-medium\", item.name));',
    '          info.appendChild(createEl(\"div\", \"text-xs opacity-70\", formatMoney(item.price)));',
    '          row.appendChild(info);',
    '          var controls = createEl(\"div\", \"flex items-center gap-2\");',
    '          var minus = createEl(\"button\", \"px-2 py-1 border rounded-md\", \"-\"); minus.type = \"button\";',
    '          minus.addEventListener(\"click\", function(){ updateQty(item.id, item.quantity - 1); });',
    '          var plus = createEl(\"button\", \"px-2 py-1 border rounded-md\", \"+\"); plus.type = \"button\";',
    '          plus.addEventListener(\"click\", function(){ updateQty(item.id, item.quantity + 1); });',
    '          controls.appendChild(minus);',
    '          controls.appendChild(createEl(\"span\", \"text-sm\", String(item.quantity)));',
    '          controls.appendChild(plus);',
    '          row.appendChild(controls);',
    '          itemsRoot.appendChild(row);',
    '        });',
    '      }',
    '      clearEl(totalsRoot);',
    '      if(cart.items.length){',
    '        var t = totals();',
    '        totalsRoot.appendChild(createEl(\"div\", \"flex justify-between\", \"Subtotal\"));',
    '        totalsRoot.lastChild.appendChild(createEl(\"span\", \"\", formatMoney(t.subtotal)));',
    '        totalsRoot.appendChild(createEl(\"div\", \"flex justify-between\", \"VAT\"));',
    '        totalsRoot.lastChild.appendChild(createEl(\"span\", \"\", formatMoney(t.vat)));',
    '        totalsRoot.appendChild(createEl(\"div\", \"flex justify-between font-semibold\", \"Total\"));',
    '        totalsRoot.lastChild.appendChild(createEl(\"span\", \"\", formatMoney(t.total)));',
    '      }',
    '    }',
    '    function setError(msg){ if(!errorRoot) return; clearEl(errorRoot); if(msg) errorRoot.appendChild(createEl(\"div\", \"text-sm text-primary\", msg)); }',
    '    var checkoutBtn = el.querySelector(\"button[data-kx-checkout]\");',
    '    if(checkoutBtn){ checkoutBtn.addEventListener(\"click\", function(){',
    '      setError(\"\");',
    '      if(!cart.kitchenId){ setError(\"Kitchen is not resolved yet.\"); return; }',
    '      if(cart.items.length === 0){ setError(\"Cart is empty.\"); return; }',
    '      if(paymentMethod === \"card\" && !successUrl){ setError(\"Checkout links are not configured.\"); return; }',
    '      var payload = { kitchen: cart.kitchenId, payment_method: paymentMethod, items: cart.items.map(function(it){ return { item: it.id, quantity: String(it.quantity), unit_price: it.price.toFixed(2), vat_rate: String(it.vatRate || 0) }; }) };',
    '      if(paymentMethod === \"card\"){ payload.success_url = successUrl; payload.cancel_url = cancelUrl || successUrl; }',
    '      fetch(normalizeBase(apiBase) + \"/api/v1/kitchenx/public/orders\", { method: \"POST\", headers: { \"Content-Type\": \"application/json\" }, body: JSON.stringify(payload) })',
    '        .then(function(res){ return res.json().then(function(data){ if(!res.ok){ throw new Error(data && data.detail ? data.detail : \"Unable to place order.\"); } return data; }); })',
    '        .then(function(data){ cart.items = []; notify(); if(data && data.payment && data.payment.requires_redirect && data.payment.redirect_url){ window.location.href = data.payment.redirect_url; } })',
    '        .catch(function(err){ setError(err && err.message ? err.message : \"Unable to place order.\"); });',
    '    }); }',
    '    update();',
    '    subscribe(update);',
    '  }',
    '  function boot(){',
    '    var menus = document.querySelectorAll(\"[data-kx-menu]\");',
    '    menus.forEach(function(el){ renderMenu(el); });',
    '    var carts = document.querySelectorAll(\"[data-kx-cart]\");',
    '    carts.forEach(function(el){ renderCart(el); });',
    '  }',
    '  if(document.readyState === \"loading\"){ document.addEventListener(\"DOMContentLoaded\", boot); } else { boot(); }',
    '})();',
  ].join('\\n');
}
